server:
  port: 8082
spring:
  redis:
    host: 127.0.0.1
    port: 16379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0